#Importing and Linking all the HDL source files used in the design
import_files -library work -hdl_source script_support/hdl/DDR_read_controller.vhd
import_files -library work -hdl_source script_support/hdl/data_unpacker.vhd
import_files -library work -hdl_source script_support/hdl/ram2port.vhd
import_files -library work -hdl_source script_support/hdl/dc_fifo.vhd
import_files -library work -hdl_source script_support/hdl/DDR_write_controller.vhd
import_files -library work -hdl_source script_support/hdl/data_packer.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_pkg.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_burst_aligner.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_register.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_fifo_sync.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_registers.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_throttler.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_upsizer.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist_write_burst_buffer.vhd
import_files -library work -hdl_source script_support/hdl/draw_assist.vhd
import_files -library work -hdl_source script_support/hdl/axi_passthru.vhd
import_files -library work -hdl_source script_support/hdl/legup_mult_pipelined.v
import_files -library work -hdl_source script_support/hdl/legup_mult_core.v
import_files -library work -hdl_source script_support/hdl/legup_mult.v
import_files -library work -hdl_source script_support/hdl/scale.v
import_files -library work -hdl_source script_support/hdl/ram_dual_port_fifo.v
import_files -library work -hdl_source script_support/hdl/fwft_fifo.v
import_files -library work -hdl_source script_support/hdl/hls_register.v
import_files -library work -hdl_source script_support/hdl/ram_dual_port.v
import_files -library work -hdl_source script_support/hdl/warp.v
import_files -library work -hdl_source script_support/hdl/data_receiver_fifo.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_NstagesSync.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_grayToBinConv.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_async.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_resetSync.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_sync.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_fwft.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_corefifo_sync_scntr.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_LSRAM_top.v
import_files -library work -hdl_source script_support/hdl/axi_lbus_ram_wrapper.v
import_files -library work -hdl_source script_support/hdl/video_axi_fifo.v
import_files -library work -hdl_source script_support/hdl/ddr_rw_arbiter.v
import_files -library work -hdl_source script_support/hdl/read_demux.vhd
import_files -library work -hdl_source script_support/hdl/read_mux.vhd
import_files -library work -hdl_source script_support/hdl/request_scheduler.vhd
import_files -library work -hdl_source script_support/hdl/write_demux.vhd
import_files -library work -hdl_source script_support/hdl/write_mux.vhd
import_files -library work -hdl_source script_support/hdl/apb_wrapper.vhd
import_files -library work -hdl_source script_support/hdl/axi_arbiter.vhd
import_files -library work -hdl_source script_support/hdl/ff_bus.vhd
import_files -library work -hdl_source script_support/hdl/vector_mux.vhd
import_files -library work -hdl_source script_support/hdl/synchronizer_circuit.vhd
import_files -library work -hdl_source script_support/hdl/pixel_average.vhd
